modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mixins]]
config = "ascendant_skills.mixins.json"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Harmfy"
description='''
Party, boss requirement, perk, and Puffish Skills integration layer for the Harmfy Ascendant Skills modpack.
'''

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="puffish_skills"
type="required"
versionRange="[0.18.3,)"
ordering="AFTER"
side="BOTH"
